# Generated by Django 3.1.5 on 2021-01-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('define', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='define',
            name='ranking',
        ),
        migrations.AlterField(
            model_name='define',
            name='downloads',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='define',
            name='pegi',
            field=models.PositiveIntegerField(),
        ),
    ]
