# Generated by Django 3.1.5 on 2021-01-18 09:54

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorDefining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('pegi', models.CharField(max_length=3)),
                ('commentCount', models.CharField(max_length=11)),
                ('downloads', models.CharField(max_length=12)),
                ('ranking', models.CharField(max_length=4)),
                ('firstHex', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('secondHex', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
            ],
        ),
    ]
